# Generated by Django 3.2 on 2022-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220411_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oiginal_bag',
            new_name='original_bag',
        ),
    ]
